### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by Dinosaurismus** [ClassiCube/MCGalaxy#1]
Is this a continuation of MCForge/MCForge-Redux? Or is it that server software for your server? 
Or is it just a fun mess-around project?

Also, the readme is not updated XD

**Comment by ghost** [comment]
It will most likely be a continuation of Redux if everything goes well. This is actually fixing Redux while offering the same features. We will switch back to .lvl from .mcf to fix some bugs and hopefully actually work on this.

**Comment by Dinosaurismus** [comment]
Also, I saw the plasmashaft reposity got deleted. why?

**Comment by ghost** [comment]
It was dead anyways..
