### ISSUE TITLE
[Reintroduced bug] /goto on unloaded maps won't work under a circumstance

### ISSUE THREAD

**Issue by FabTheZen** [ClassiCube/MCGalaxy#100]
Using /goto for an unloaded map will say "map is already loaded", if a map which name contains the unloaded map is already loaded. This was probably reintroduced by a supposed fix for level loading a month ago

**Comment by UnknownShadow200** [comment]
No, it was reintroduced because I fixed Level.Find to use shortcuts properly. Will fix though.

**Comment by UnknownShadow200** [comment]
Fixed by 063c8794f5b64c4b05798993a7a6200eead44e2a.
