### ISSUE TITLE
[Hard to reproduce] Sometimes block changes won't save

### ISSUE THREAD

**Issue by FabTheZen** [ClassiCube/MCGalaxy#101]
This has happened multiple times in my server, I think it's lag-related, maybe blocks don't save properly due to buffers not flushing correctly. What I see is, a person is invisible or can't see others, and block changes they make are not visible, yet chat doesn't lag. Once this person disconnects or teleports to someone else, they'll be "moved" in the same map without their changes

**Comment by UnknownShadow200** [comment]
Fixed in 0eaa99d2e5954a6f62242838e2c45275f1d7403d.
