### ISSUE TITLE
Command to hide from all lower than admin ranks.

### ISSUE THREAD

**Issue by UnknownShadow200** [ClassiCube/MCGalaxy#117]
(not just lower ranks, could be done via modifying /ohide and Player.CanSee)

Requested by FabTheZen.

**Comment by Peteys93** [comment]
Basically have this done.  Should players who are not admin have the option to admin hide on themselves, or only if an admin uses /ohide on them?

**Comment by UnknownShadow200** [comment]
What I was thinking is that /ohide hides the target to all players below the caller's rank, instead of the target's rank.

**Comment by Peteys93** [comment]
Ah, that makes more sense.  I've finished it. Will pull request tomorrow.

**Comment by UnknownShadow200** [comment]
Ah cool - thanks for all the pull requests.
