### ISSUE TITLE
Muted people can be impersonated.

### ISSUE THREAD

**Issue by Goodlyay** [ClassiCube/MCGalaxy#123]

**Comment by Peteys93** [comment]
Changed.

Also, /imp playeronserver without a message specified gave this error, which I have fixed.

Will pull request.

Type: IndexOutOfRangeException
Source: MCGalaxy_
Message: Index was outside the bounds of the array.
Target: Use
Trace:    at MCGalaxy.Commands.CmdImpersonate.Use(Player p, String message) in c:\Users\Patrick\Desktop\MCGalaxy-master\Commands\other\CmdImpersonate.cs:line 30
   at MCGalaxy.Player.<>c__DisplayClassc.<UseCommand>b__b() in c:\Users\Patrick\Desktop\MCGalaxy-master\Player\Player.Handlers.cs:line 1325

**Comment by UnknownShadow200** [comment]
Fixed by 07fe07aca2b7bbe6674a7e06e6a3f44825eed74a.
