### ISSUE TITLE
Joining a map with a portal block fails to load the colors for that map.

### ISSUE THREAD

**Issue by Goodlyay** [ClassiCube/MCGalaxy#13]

**Comment by Venom983** [comment]
Could you provide the steps you took? Because from what I have tested, environment colors load just the same as /goto when using portal blocks.

**Comment by Goodlyay** [comment]
Yeah I can't reproduce it now. It must have been fixed and I didn't test since it was an issue.

**Comment by Venom983** [comment]
Could you close the issue then please?

**Comment by Goodlyay** [comment]
I wasn't aware it was possible to close my own issues.
