### ISSUE TITLE
Open file

### ISSUE THREAD

**Issue by 1stupidname** [ClassiCube/MCGalaxy#136]
I'm running on Win XP.  (very clean system)
- [x] When using "load"  button from the custom command creation page, if you browse to a different directory looking for the file to load, the server thinks you are changing the servers route directory and try's to create a new "levels" sub directory at where ever it is you have browsed too.  
  This causes lots of other weird problems.  
- [ ] The "X", in the top left corner closes the server.   This is what it should do.  However, many (most) other server/damons tray have chosen to make the X minimize the server to the system tray.   It would be nice if the MCGalaxy server did the same.   

Note:  Have just finished tasting evaluated MCGalaxy, MCDzienny, fcraft, D3_Classicube, 800Craft, and LegendCraft.  MCGalaxy came out on top, but probably you already new that.

**Comment by UnknownShadow200** [comment]
For completeness I should mention that [ProCraft](https://github.com/123DMWM/ProCraft) is still an actively developed fork of fCraft and has many more features compared to the other fCraft forks.

Fixed the first issue, will see about the second point.

**Comment by UnknownShadow200** [comment]
@Goodlyay 
Why close? second point was not fixed

**Comment by Goodlyay** [comment]
I don't think it's a valid point -- X should close a window. That's what it's for. There is even a warning if you accidentally clicked it too.

**Comment by UnknownShadow200** [comment]
There's a number of applications where X doesn't close the application, but the other classicube server softwares has X close them too.. so I guess we should go for consistency.

**Comment by Goodlyay** [comment]
Frankly X should always close applications. It's pretty annoying when you have to go through loopholes to close something because the people who made the program think they know better than what the user wants to do. (Looking at Skype and Discord for example...)

**Comment by 1stupidname** [comment]
I should start that I agree with the points made.  The idea of the X minimizing the window to the bar is probably a poor way of expressing the underlining idea.  The motivation behind my suggestion was compliance with what appears to be an emerging defacto standard for the behavior of the "X". 

I believe the following explains the thinking that has led to this standard.

The windows tray existed for holding access icons to active daemons.   When clicking on the icon a GUI for accessing the daemon is opened.   When clicking on the "X" the GUI is closed but not the underlying daemon.  This makes perfect sense when the underlying daemon has been launched as a service.   Things may be less obvious when the GUI for accessing the daemon is the program that launches the daemon.

The tray icon should, to be consistent with other software, provide a right click option that produces a menu with among other things the option of closing the daemon.   

Examples, of software taking the above approach are the Microsoft networking daemons, clock, volume control, Norton antivirus, Taxiti and so on.  

Currently, the warning issued when I click on the "X" is sufficient to remind me that this software behaves differently most other software.  

It should be noted I spend a disproportionate amount of time accessing and monitoring various daemons running on dozens of remote computers.

**Comment by UnknownShadow200** [comment]
Tray icon already provides option of closing server and reopening the gui.

A bit of a generalisation, but probably an accurate one - most of the people who are using the gui (instead of CLI and screen on linux) aren't people who frequently use server daemons. So I'd rather go for consistency with other classicube server software guis, where X closes them.
