### ISSUE TITLE
The fog color of a map saves as the cloud color of the map

### ISSUE THREAD

**Issue by Goodlyay** [ClassiCube/MCGalaxy#14]

**Comment by ghost** [comment]
It saves correctly for me, does this still happen with 1.7.0?

**Comment by Goodlyay** [comment]
Yes, it does. Try this: go to a map, and use /env l cloud 000000. Leave the map, let it unload, then come back. The fog will also be 000000. Also, for this to happen I think you need to have tried to change the fog color at least once beforehand.

**Comment by Venom983** [comment]
Yeah I was able to reproduce. The issue being that the "fog" case doesn't update or save in the properties, wheres clouds modifies both cloud and fog color.

Edit: Should be fixed in the newly submitted pull.

**Comment by ghost** [comment]
Thanks
