### ISSUE TITLE
Replaceall type commands using wrong number

### ISSUE THREAD

**Issue by Peteys93** [ClassiCube/MCGalaxy#140]
Commands like replaceall and unflood are using the number 2097152 (in 128x128x128) 262144 (in 64x64x64) when trying to replace, even if there is only 1 of that type of block on the map.

Seems to be counting the air, rather than the block the user is trying to replace

**Comment by UnknownShadow200** [comment]
This works as intended, as part of the rewrite of the draw operations to support brushes, some brushes (such as random brush) will not update every block affected, thus we can't accurately calculate how many blocks will be affected in advance.

Might be nice to have it say at the end of the draw operation how many blocks were affected though.

**Comment by Peteys93** [comment]
The issue here is with limits. Since /ra is counting air instead of the block to be replaced, if the player has a lower building limit than the amount of air on the map, they will not be able to /ra or /unflood.

http://puu.sh/otvKH/6a0ba9cd3a.jpg
http://puu.sh/otvMz/3b49f7e7aa.jpg

Is there a /rb equivalent to /ra block1 air? -- i.e. it replaces all blocks of type block1 with air in the map, without having to place edges

Perhaps we could just make /ra a shortcut for that if so.

**Comment by UnknownShadow200** [comment]
/ra is now just essentially a shortcut for /brush replace then /cuboid.
