### ISSUE TITLE
Blocks such as nerve_gas and air_switch issue

### ISSUE THREAD

**Issue by Peteys93** [ClassiCube/MCGalaxy#141]
Blocks that should turn to air when placed don't seem to be doing so.  They still work as they should if you manually break them (i.e. left click them after placing), but they should automatically turn to air (and used to) I think.

**Comment by UnknownShadow200** [comment]
Checked and MCForge doesn't turn them into air when placed. 
I still think it's handy to visually see that the air_switch blocks were actually successfully placed.

**Comment by Peteys93** [comment]
Fair enough, felt like I thought I remembered they autochanged in the past (like before cpe, when 'air' was changed), but I may have just been thinking of commands like /messageblock air.

**Comment by UnknownShadow200** [comment]
Still think this should be toggleable.

**Comment by UnknownShadow200** [comment]
Implemented in bb311668897b3204b926061953e4dad2c46f96a8
