### ISSUE TITLE
Authentication for old MC users (pre-ClassiCube users)

### ISSUE THREAD

**Issue by AnthonyANI** [ClassiCube/MCGalaxy#158]
I took notice of the + added onto users, presumably for preventing server abuse via creating a ClassiCube account using the same username of a Minecraft account and logging in to gain access to privileges once granted to such a Minecraft account.  However, this + is causing legit users to lose their user stats (login times, blocks modified, zones, ranks, etc), which again was presumably the point.  Is there some way to possibly verify the older MC users (even though the login now goes through ClassiCube)?  If not, what I have done for my local copy is put in some lines of code to read a text file with usernames to trust, thus not adding the + to such users (because I'm a bit too lazy for anything else), so I thought I'd share the idea.  Maybe using the Minecraft Universally Unique Identifier can help verify users in the future at least.  Thanks.

**Comment by UnknownShadow200** [comment]
There is no automated way (that I can think of) to verify that a classicube account belongs to the same person with that minecraft.net account, since emails are not publicly exposed.

I do think there should be some sort of /transferinfo command though for cases like this.

**Comment by UnknownShadow200** [comment]
As a follow-up, in the meantime you can use /pe to manually adjust player stats.
