### ISSUE TITLE
Collection of bugs and features 

### ISSUE THREAD

**Issue by FabTheZen** [ClassiCube/MCGalaxy#16]
This is a set of bugs and requested features from players and myself, sorted by importance and divided, respectively, in bugs and features.

PasteBin link: http://pastebin.com/fWC6kYqS

**Comment by Venom983** [comment]
Just a little update:

Bugs/Features Completed-
Make a better help menu (a la ProCraft/LegendCraft) - Added
Map texturepack should be showed in /mapinfo - Added
Add /xtitle, /xnick, /xcolor, /xtcolor for self-applied title etc - Added
Warns should show on IRC - Fixed
Gui is still broken (doesn't save propertes) - Fixed
/clones doesn't work with + (? tommy) - NotBroken
Many commands fail from console (/whoip) - NotBroken
/hide doesn't auto-opchat hiders AND THEY GO AUTO AFK! - Fixed
%r at the end of nicknames AUTOMATIC - Added
Title color works bad(I have to match title color with the last color code of it) - Fixed
New bug: when someone joins a level, it reloads all chunks - NotBroken
First /os map should be called <username>+1 (to avoid loading issues) - Fixed
Fix /env l border not changing border block - NotBroken
Check if /lockdown works good (should be fixed) - NotBroken
Fix /os kickall (send all players to /main) - Fixed
/model doesn't change until you change map (ONLY own model?) - Fixed
Reintroduce all emotes - Added
Reintroduce "/weather" (or /env l weather) - Exists
Add /os commands: motd, env,weather, texture, pervisit, gun - Added
/z etc should also accept block ID (minor) - Added
/env presets Added

**Comment by FabTheZen** [comment]
thank you! :smile:
