### ISSUE TITLE
/circle command where 1st block takes the centre and 2nd block takes the radius

### ISSUE THREAD

**Issue by empyrrean** [ClassiCube/MCGalaxy#170]
i know that /sphere exists but it does a poor job of making a 2d circle at times, it's basically a cuboid and for some things its useful, but sometimes you cant tell where the circle will end up when you cuboid it

**Comment by UnknownShadow200** [comment]
~~As a temp work around you can use "/draw [radius] sphere", which treats the first coordinate given as the centre.~~
Oops you were talking about 2D circle,ignore that.
