### ISSUE TITLE
[Suggestion] Sortable Inventory

### ISSUE THREAD

**Issue by FabTheZen** [ClassiCube/MCGalaxy#179]
With a growing number of custom blocks, a server might (and probably will) find itself with a messy inventory. It would be nice to be able to move blocks around in the inventory screen, to avoid having to manually edit JSON block definition files, thus also breaking previously built maps.

**Comment by Propolys** [comment]
Is this even possible client-side?

**Comment by Venom983** [comment]
It would be if you made modifications to the client and server's BlockDefinition packet. Easiest solution (in my mind), would be adding an extra byte within the packet that identifies the "category" of that block. Then other little miscellaneous tweaks like "0" for unsorted. There would also need to be a server-side implementation so users could choose what the category titles would be etc. It is possible, it just depends on how much effort is willing to be made to implement this idea.

**Comment by Propolys** [comment]
I was aware that by modifying the protocol itself it could be done.
Anyway, this issue/suggestion would better be posted on the client repository as that's what needs this feature first.

**Comment by FabTheZen** [comment]
A non intrusive way to sort inventory could be a new block property that defaults to the block ID, that way we could individually change the "block priority" and make block appear wherever we want

**Comment by UnknownShadow200** [comment]
Implemented in e95672c824a44cdee469ae2bcf55087959ebed0e and https://github.com/UnknownShadow200/ClassicalSharp/commit/42e1fdc3d167269a7b9570d2d9ec9ef28615f358
