### ISSUE TITLE
"Level may not have been created"

### ISSUE THREAD

**Issue by Jake1702** [ClassiCube/MCGalaxy#285]
On trying to generate a new map for my server, I constantly get "Level creation failed. Are you sure you didn't leave a box empty?" and then when I close that "Level may not have been created." YES, I filled in ALL  boxes, everything should be working.

**Comment by UnknownShadow200** [comment]
People actually use the gui for generating a level? welp.
That message is highly misleading, as checking if boxes are empty is done before trying to create a level. However, it shows that message for any error that occurs.

How big is the map you generated? The most likely cause of that message showing is that you have multiple very large loaded worlds, tried to generate another large world, and the server ran out of memory.
