### ISSUE TITLE
Ability to whitelist clickable blocks for /adventure mode

### ISSUE THREAD

**Issue by xnotx123** [ClassiCube/MCGalaxy#288]
/adventure might need to be changed a bit to compensate:
/adventure [command] [args]
Disables all hax on a map.
Commands: on, off, whitelist
Type /help adventure [command] for more details
Usable by: Moderator+
Shortcuts: /ad
-------------------------------------------
/help adventure whitelist :
/ad whitelist add [id] - allows a block to be clickable in adventure mode
/ad whitelist remove [id] - disallows a block to be clickable in adventure mode
/ad whitelist list - displays all current whitelisted blocks
-------------------------------------------
Just a quick idea of how the command could be modified to compensate for a whitelist.

**Comment by UnknownShadow200** [comment]
/adventure is not an MCGalaxy command, it's a custom command only for Not Awesome as far as I know.

**Comment by xnotx123** [comment]
Ah, alright. Would there need to be changes made to Classicalsharp for this mechanic to work?

**Comment by UclCommander** [comment]
No. Not Awesome would have to make these changes.
