### ISSUE TITLE
Cannot remove advbuilder rank

### ISSUE THREAD

**Issue by MrOnlineCoder** [ClassiCube/MCGalaxy#292]
Hello. I am trying to remove AdvBuilder rank, but it appers again after Apply. Maybe UI bug.

Video: https://youtu.be/G-XuwxzWtkg

**Comment by UnknownShadow200** [comment]
ranks with banned/guest/builder/advbuilder/operator/superop permission levels are currently always required, however you can rename these ranks to something else.

**Comment by MrOnlineCoder** [comment]
Ok, let it be, but I have 2 AdvBuilders in the list!

**Comment by Goodlyay** [comment]
You can remove the duplicate one that does not use permission of "50."

**Comment by MrOnlineCoder** [comment]
I can't. It appears again after I click Apply. I even tried to remove that rank from ranks.proporties directly, but it didn't work

**Comment by UnknownShadow200** [comment]
Please upload your rank.properties somewhere for us to look at, I'm able to delete duplicate ranks named advbuilder fine.

**Comment by MrOnlineCoder** [comment]
Try that: http://fex.net/load/930442172856/319988

**Comment by UnknownShadow200** [comment]
As a temporary workaround, deleting both advbuilder ranks in the gui, then clicking 'apply' seemed to fix the issue. 

After doing so, you can then rename the advbuilder rank with permission level 50 to something else, and then create an advbuilder rank with whatever permission level you want.

edit: will see if I can make it so ranks with builder/advbuilder/operator/superop permission levels aren't mandatory

**Comment by MrOnlineCoder** [comment]
Ok, thanks, but why theese ranks are required?  I think user can have as many ranks as he want.

**Comment by UnknownShadow200** [comment]
It used to crash on startup if there weren't ranks with those permission levels didn't exist, but as of most recent commits it works without them now.

**Comment by UnknownShadow200** [comment]
Fixed as of the latest release, only banned/guest/nobody ranks are required now.
