### ISSUE TITLE
custom block slab stacking for /blockproperties

### ISSUE THREAD

**Issue by UnknownShadow200** [ClassiCube/MCGalaxy#330]

**Comment by UnknownShadow200** [comment]
Good enough for you @Goodlyay, or do you still want client side block stacking too?

**Comment by Goodlyay** [comment]
Client side is much more ideal, as server side stacking can be annoying when you were just trying to place a slab on top of the slab and not have it get combined

**Comment by UnknownShadow200** [comment]
I don't see how that's different though, it would stack the two slab blocks client side anyways.. ?

**Comment by Goodlyay** [comment]
No. Client side slab stacking would only combine the slabs if you place a slab into the actual empty space left by the slab in a tile. "stacking" is a bit of a misnomer in this case, it's more like slab combining.

**Comment by Goodlyay** [comment]
For example of this done, see Minecraft Premium

**Comment by UnknownShadow200** [comment]
Yeah, way premium does it is better.

However, I don't really think doing it client-side would work well though. Since slab stacking will still be done by server softwares (all fcraft and mclawl forks), and disabling slab stacking would cause issues for people using older client versions.

**Comment by Goodlyay** [comment]
You don't have to disable slab stacking server-side for it to work client side. It's just "nicer" if it is disabled server side so you don't have slabs falling down onto others when you wanted it to just sit on top.

**Comment by UnknownShadow200** [comment]
My point was that if it is not disabled server-side, it still does the double slab stacking anyways, defeating the purpose of implementing slab-combining client side.

**Comment by Goodlyay** [comment]
This still doesn't defeat the purpose of combining it client side.
Take these for instance:

![image](https://user-images.githubusercontent.com/7892772/27523505-708c87ba-59e2-11e7-8441-72a9bc2be112.png)
You can't combine these by placing slabs into the empty slots without clientside. Also, server doesn't even have upside down stacking.

Also, stacking becomes much much slower and frustrating if it's only done server-side, especially if you have poor ping
