### ISSUE TITLE
Hackrank should change entity nametag colour and tab list name colour

### ISSUE THREAD

**Issue by UnknownShadow200** [ClassiCube/MCGalaxy#440]
Looks more convincing that way

**Comment by Goodlyay** [comment]
Can we get similar functionality with /fakerank? 👍

**Comment by UnknownShadow200** [comment]
Player.Message(p, "%HSends a fake rank change message.");

I thought its purpose was just to send a message though?

**Comment by Goodlyay** [comment]
Its purpose is to trick people into thinking they got ranked. The help of course only describes what it currently does

**Comment by UnknownShadow200** [comment]
Not sure for what the new help message should be then.

**Comment by Goodlyay** [comment]
"Gives [player] the appearance of being ranked."?

**Comment by UnknownShadow200** [comment]
done

**Comment by Goodlyay** [comment]
Awesome. I should probably stop asking for such trivial things though lol
