### ISSUE TITLE
Adding equal (=) sign to the server name causes the server name to reset itself.

### ISSUE THREAD

**Issue by TheRealPear** [ClassiCube/MCGalaxy#443]
Like I said in the title, it changes back to _[MCGalaxy] Default_. I don't think it's a high priority, but I think that it should be fixed.

**Comment by UnknownShadow200** [comment]
wat even

**Comment by Goodlyay** [comment]
It tells you why this happens in the console log. "=" is not an allowed server name character.

**Comment by TheRealPear** [comment]
do I have to explain it more in detail?

**Comment by UnknownShadow200** [comment]
@TheRealPear  No. I already fixed the issue.

**Comment by TheRealPear** [comment]
Oh, well the problem is still on MCGalaxy 1.8.9.0 unless it was fixed on the dev version?

**Comment by UnknownShadow200** [comment]
Well, yeah the problem will still be in 1.8.9.0, I only fixed the issue after 1.8.9.0 had already been released.
