### ISSUE TITLE
add more parameters to /highlight

### ISSUE THREAD

**Issue by CleverDino** [ClassiCube/MCGalaxy#446]
* /highlight area <playername> <timespan> = Highlights changes based on the selection made with two blocks
* /highlight pos [block radius] <playername> <timespan> = highlights changes in a certain radius based on current position

**Comment by UnknownShadow200** [comment]
will look at soon

**Comment by UnknownShadow200** [comment]
/highlight area is implemented
/highlight pos [radius] isn't really necessary now - can do /highlight area, /m ~[-radius], /m ~[radius]

Marking as closed.
