### ISSUE TITLE
Copy @ issue

### ISSUE THREAD

**Issue by Goodlyay** [ClassiCube/MCGalaxy#452]
using /copy @ then doing the third click will result in:

----5/31/2017 12:56:15 AM ----
Type: NullReferenceException
Source: MCGalaxy_
Message: Object reference not set to an instance of an object.
Target: SelectionBlockChange
Trace:    at MCGalaxy.Player.SelectionBlockChange(Player p, UInt16 x, UInt16 y, UInt16 z, ExtBlock block)
   at MCGalaxy.Player.ManualChange(UInt16 x, UInt16 y, UInt16 z, Byte action, ExtBlock block, Boolean checkPlaceDist)
   at MCGalaxy.Player.HandleBlockchange(Byte[] packet)

-------------------------

The object is copied, but the @ takes no effect, and it pastes from the usual corner.

**Comment by UnknownShadow200** [comment]
Reproducible, looking into fix

**Comment by Goodlyay** [comment]
Thanks for the swift fix!
