### ISSUE TITLE
missing player data

### ISSUE THREAD

**Issue by skititlez** [ClassiCube/MCGalaxy#453]
players do not showed up logged into the server
and IPs do not show up

-Apparently there was a clone of my server floating around hence why i wasn't able to see anybody-

**Comment by UnknownShadow200** [comment]
@skititlez

Accidental close, or issue resolved?

**Comment by UnknownShadow200** [comment]
Oops sorry for unnecessary mention. The edit didn't show in the notification email I received.

**Comment by skititlez** [comment]
nah its fine. and its it is was resolved. Had to do some indepth digging, Apparently long ago we created an MCredux server to do some testing and it a to the T clone of the MCGalaxy server. without my knowing it was just running as a process in the background of the server and would startup on reboot but not show a GUI or any signs that it was active. I removed the process from startup and setup Galaxy as the primary as it should be.
