### ISSUE TITLE
Commands in console no longer show timestamp 

### ISSUE THREAD

**Issue by Goodlyay** [ClassiCube/MCGalaxy#455]
[9:28:11 PM] <StarlightGlimmer+> well that's basically just /torus but nice
[9:28:13 PM] killerwhale123+ was unloaded.
XenonMan+ used /help torus
StarlightGlimmer+ used /sphere hollowcircle
StarlightGlimmer+ used /sphere hollowcircle
Zed714+ used /cuboid 
XenonMan+ used /cuboid aor
XenonMan+ used /cuboid air
Zed714+ used /cuboid 
Zed714+ used /cuboid 
Zed714+ used /cuboid 
Zed714+ used /cuboid 
Zed714+ used /cuboid 
Zed714+ used /cuboid 
Zed714+ used /cuboid 
Zed714+ used /copy cut

**Comment by Goodlyay** [comment]
Not sure if intentional.

**Comment by UnknownShadow200** [comment]
uhhhhhhhhhhhhhh

Oops?

**Comment by UnknownShadow200** [comment]
Unintentional bug from when I rewrote all the logging in 8af7ce291b162764d1867101e1878d1a635a94b9
