### ISSUE TITLE
Bots in Classic Revival server causes massive amounts of ping?

### ISSUE THREAD

**Issue by Goodlyay** [ClassiCube/MCGalaxy#459]
Map is called so4repfight. Rest of the server I get around 100 ping, in that map I get around 3,000
Happens to other players as well. Physics are OFF.

**Comment by Goodlyay** [comment]
Well apparently it was bots causing the slowdown, there were around 50 on the map. When removed it fixed it. https://github.com/Hetal728/MCGalaxy/issues/205 Related?

**Comment by UnknownShadow200** [comment]
Does sending chat have 3 second latency

**Comment by Goodlyay** [comment]
Yeah, somewhere around that time.

**Comment by UnknownShadow200** [comment]
I added 100 bots to a map on my VPS. Still 200ms ping.

However, bots are extremely inefficient with position updates. They always send an absolute teleport packet (no relative, still send a packet even if not moving), each bot sends their own absolute teleport packet.

**Comment by UnknownShadow200** [comment]
ee43f5f5f7d4834d3a346beffa38e34e2ede33bc and 2766924ed7355167e3b660d184b5f7707f75e76a
