### ISSUE TITLE
No way to see what the current limits are in /limit?

### ISSUE THREAD

**Issue by Goodlyay** [ClassiCube/MCGalaxy#460]
I always get stuck trying to tell people what size map they can make because I'm not sure if there's a way to check what the limits are.

**Comment by UnknownShadow200** [comment]
Just do /limit [type] without an argument.

**Comment by Goodlyay** [comment]
How strange, I remember trying this before with no luck. Thanks though!

**Comment by UnknownShadow200** [comment]
I don't think it works with the drawlimit or maxundo types, /help ranks works for them.
