### ISSUE TITLE
/limit rt (reload threshold) should be based on size of map

### ISSUE THREAD

**Issue by Goodlyay** [ClassiCube/MCGalaxy#472]
For example, in a large map like NewValeria, reloading the map can easily take much more time than it would normally save due to map loading times.

**Comment by UnknownShadow200** [comment]
Hm need to consider small maps like 32^3 still

**Comment by Goodlyay** [comment]
Yeah sounds like a map like that should never need a reload

**Comment by UnknownShadow200** [comment]
Aye, but my point was changing reload threshold to be a % of map size isn't enough.

**Comment by Goodlyay** [comment]
It has to be based on some kind of equation of time spent: map reload time (Is this even possible to predict?) and the time it takes to complete the draw operation.

**Comment by UnknownShadow200** [comment]
Might be possible but yuck

Maybe reload_reshold = max(fixed_threshold, percent_threshold * map_volume)

**Comment by UnknownShadow200** [comment]
@Goodlyay 

What limit do you currently have set for /limit rt?

Also I'm still deciding on name for the limit, maybe /limit rv/reloadvolume

**Comment by Goodlyay** [comment]
My limit is 10,000. I believe that's the default?

**Comment by UnknownShadow200** [comment]
Yeah. The thing is that with a a 1% percent_threshold, reload_threshold for a 512^3 map spirals up to 1,342,177, way more than 10,000

**Comment by Goodlyay** [comment]
I would assume that the reload threshold would no longer be a needed option once it's based on the map reload times.

**Comment by UnknownShadow200** [comment]
I'm not basing it on map reload time, I'm basing it on what I mentioned in my comment 6 days ago.

**Comment by Goodlyay** [comment]
What I mean is that if you have a way to calculate if it's faster to reload the map or let the draw operation continue, there's no reason to let the user have any say in the matter, since they will most likely just mess it up.

**Comment by UnknownShadow200** [comment]
As the draw operation changes the blocks, that changes how well the map ends up being compressed, consequentially changing how long it takes to reload.

Which also means of the same volume will have different reload thresholds depending on how well they compress, which seems counter-intuitive.
