### ISSUE TITLE
Killer door_obsidian blockprop not working?

### ISSUE THREAD

**Issue by Goodlyay** [ClassiCube/MCGalaxy#473]
/blockprops core door_obsidian killer
/blockprops core door_obsidian deathmessage @p was %csmashed %Sin a closing door.

No result when walking into the doorway.

**Comment by UnknownShadow200** [comment]
It's because the gui changes Block.Props, but each level now maintains their own BlockProps array. (So custom /lb can override core blocks).

As a temp workaround restarting will fix, I'm working on a proper fix currently.

edit: problem also happens with /blockprops core
