### ISSUE TITLE
Add bezier curve build command

### ISSUE THREAD

**Issue by WolfgangNS** [ClassiCube/MCGalaxy#474]
As suggested by Starlightglimmer and Empy

**Comment by UnknownShadow200** [comment]
I really need to put up my local todo list on github heh.

Issues:
a) Should it only support quadratic bezier curves, or all curves
b) How is the easiest way to visualise what effect the control points will have on the actual curve

**Comment by WolfgangNS** [comment]
a) Quadratic bezier curves on any plane.
b) Specify three points by colored blocks, then type /confirm or /cancel (kind of like with /portal multi).
Also, Star said a live preview would help, meaning that the curve draws each time you place an anchor point. That might mean you'll need to store an array of the previously existing blocks that the curve is replacing, in order for a /cancel to work.

**Comment by WolfgangNS** [comment]
Correction: The endpoints wouldn't need to be specified by green or red. Just endpoints first and anchor point last. And by "any plane", I only meant XY, YZ, and XZ.
 
I'm wondering how you would most efficiently calculate the "t step" size for a bezier.

**Comment by UnknownShadow200** [comment]
I feel the drawn curves are still too thick.
