### ISSUE TITLE
/delay should use milliseconds

### ISSUE THREAD

**Issue by Goodlyay** [ClassiCube/MCGalaxy#475]
More precise control of the delay you want.

(Also, all the commands I used with /delay are now broken because mine used milliseconds.......)

**Comment by UnknownShadow200** [comment]
The question is what suffix should be for milliseconds - 's' is used for seconds and 'm' for minutes already.

**Comment by Goodlyay** [comment]
It should just use milliseconds with the number you input, no need for suffixes

**Comment by UnknownShadow200** [comment]
GetTimespan doesn't support that. You also provide a default suffix (such as 'm'), which means an input such as "1000" is treated as "1000m".

I could modify the code to support a two-letter suffix and make 'ms' the default though.

**Comment by Goodlyay** [comment]
That would be fantastic, thanks
