### ISSUE TITLE
$serverip is non-executable

### ISSUE THREAD

**Issue by xnotx123** [ClassiCube/MCGalaxy#484]
The console instead executes $server with "ip" tagged at the end of it.
e.g. "Not Awesome 2ip"

**Comment by UnknownShadow200** [comment]
Need to modify MCGalaxy to retrieve server's external IP from classicube.net to get it working.

Not sure if it's really that useful though

**Comment by Goodlyay** [comment]
It's not useful. I suggest removing it entirely.

**Comment by UnknownShadow200** [comment]
$serverip was removed in commit 306c3d9ec335fea9c101b385c858dcc9d8aa2cea.
