### ISSUE TITLE
Able to login twice as the same player.

### ISSUE THREAD

**Issue by UnknownShadow200** [ClassiCube/MCGalaxy#49]
![screenshot_22-10-2015-11-25-37](https://cloud.githubusercontent.com/assets/6509348/10654007/c2d0da72-78b0-11e5-969f-d7d2e667ee9c.png)

This only seems to happen when connecting to servers located far away. I was unable to reproduce this on a locally hosted server.

**Comment by ghost** [comment]
My guess is the players are joining at the same millisecond (Due to latency). I'll attempt to cook up a fix for this. (Also love the italicized feet position)

**Comment by Venom983** [comment]
This has happened in other mclawl forks as well. It's also the same second, not specifically millisecond.

(18:30:04) x connected to the server.
(18:30:04) x connected to the server.
(18:30:05) UnknownShadow200+ [x] has joined the server.
(18:30:06) UnknownShadow200+ [x] has joined the server.

(08:52:02) x connected to the server.
(08:52:03) x connected to the server.
(08:52:04) venom983+ [x] has joined the server.
(08:52:04) venom983+ [x] has joined the server.
