### ISSUE TITLE
Commands need to have a toggle for useable in MBs regardless of category

### ISSUE THREAD

**Issue by Goodlyay** [ClassiCube/MCGalaxy#490]
For example, /deletelvl can be used inside message blocks where a staff could accidentally walk into it.

**Comment by UnknownShadow200** [comment]
Easy enough to change the core commands, but custom commands will need to be specifically fixed up.

**Comment by UnknownShadow200** [comment]
Although, you have to be able to use /deletelvl already to be able to put it in a message block.
