### ISSUE TITLE
Pforwarding on MCGalaxy 1.8.9.6

### ISSUE THREAD

**Issue by ghost** [ClassiCube/MCGalaxy#492]
When I start a server, it says it's not pforwarded. When I port forward it from the properties then restart MCGalaxy, it still not works.. Please help me!!
Thanks, Kalsep

**Comment by Goodlyay** [comment]
You need to go to your router settings to port forward. MCGalaxy cannot do it for you. 

Tutorials: https://portforward.com/

**Comment by UnknownShadow200** [comment]
Not all routers support automatic UPnP port forwarding, or have UPnP enabled. As goodlyay mentioned, you're better off port forwarding directly via your router.
