### ISSUE TITLE
Problem with IP

### ISSUE THREAD

**Issue by ghost** [ClassiCube/MCGalaxy#493]
Hey, I port forwarded successfully (NOT ON MCGALAXY), but I have a problem. When it starts, it will start with a different IP but with the same port I forwarded. But, I can't change the IP to where I port forwarded. The hell is going on?! Please help me. Thank you.

**Comment by UnknownShadow200** [comment]
Tried but failed to identify cause of the issues with your router, nothing more can be done unfortunately. Sorry.
