### ISSUE TITLE
Lose connection from my server

### ISSUE THREAD

**Issue by Mogu94** [ClassiCube/MCGalaxy#495]
After exactly 20 minutes (I mean on the dime, It's crazy) I lose connection to my server and the game asks me if I want to reconnect. The server is still up and nothing else is wrong. Could this be a port forwarding problem or something to do with bandwidth? I'm completely unsure as to why this happens.

I made port forward entries for 25565 on my router and modem, can supply images if need be. Made one entry for TCP and one for UDP for each on both router and modem. I enabled UPnP on my router to see if that magically fixed this but it did not.

Edit: To my knowledge, I have the latest MCGalaxy (1.8.9.7).

**Comment by UnknownShadow200** [comment]
https://github.com/UnknownShadow200/ClassicalSharp/issues/482
