### ISSUE TITLE
Console error spam. (Something to do with .NET Framework?)

### ISSUE THREAD

**Issue by MasterlazorX** [ClassiCube/MCGalaxy#502]
Happens on startup, on random times while the server is running, and when players sometimes use commands or enter another world. This error occurs randomly and on startup, it spams the console to hell for a few seconds.

I think it has something to do with .NET framework, but I'm unsure what to do to get to the bottom of this. I've tried reinstalling .NET framework but I'm unsure if this is on my part or the server's. 
Any suggestions?

-------------------------
----1/11/2018 5:54:18 PM ----
Type: FileLoadException
Source: MCGalaxy_
Message: Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration information.
Target: CreateConnection
Trace:    at MCGalaxy.SQL.SQLiteParameterisedQuery.CreateConnection(String connString)
   at MCGalaxy.SQL.ParameterisedQuery.Execute(String query, String connString, Boolean createDB)
   at MCGalaxy.SQL.Database.DoDatabaseCall(ParameterisedQuery query, String sql, Boolean createDB, DataTable results, ReaderCallback callback, Object[] args)

-------------------------

**Comment by UnknownShadow200** [comment]
No real idea why that happens, apparent fix is changing contents of MCGalaxy.exe.config to

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup useLegacyV2RuntimeActivationPolicy="true">
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0"/>
  </startup>
</configuration>
```

**Comment by UnknownShadow200** [comment]
@MasterlazorX 

Did that fix it, or does the issue still happen?

**Comment by MasterlazorX** [comment]
It seems to have fixed the issue. Thanks!

**Comment by UnknownShadow200** [comment]
System.Data.SQLite is no longer separate dll
