### ISSUE TITLE
Cannot delete level named "main"

### ISSUE THREAD

**Issue by htravis123** [ClassiCube/MCGalaxy#505]
Hello. I messed up something in my world and was going to delete and replace it with a new map. But I couldn't see a delete button anywhere. Can you help me?

**Comment by htravis123** [comment]
Also, I tried deleting the level files, but that didn't work.

**Comment by UnknownShadow200** [comment]
Normally you can use /deletelvl [map name], but that won't work on the main level. So you can either:
- Change main to another map by doing /main [map name]
- Shut off server, delete main.lvl in levels folder, which will cause it to be regenerated

I'm guessing you did one of those already though?
