### ISSUE TITLE
Importing a world from another server breaks the blockdef

### ISSUE THREAD

**Issue by TheRealPear** [ClassiCube/MCGalaxy#510]
I ran into this issue when I was trying to import the level `_pear+` from the server, Not Awesome 2 to another server of mine. I used ClassicalSharp's (now ClassiCube) level saving feature and used the server software to load it. All I did was that I turned off the server after I imported the level, deleted the old `global.json` and renamed `lvl.pear+.json` to `global.json` and started it up.

The new blocks were added, but it was in the wrong ID. [Picture of example here
](https://i.imgur.com/wWdJcRr.png). Some blocks like "Lined stone" in the first image were even removed on my server, shown on the 2nd image.

The same issue came up when I tried in singleplayer, so I'm not really sure if this is either MCGalaxy or the client causing the issue.

**Comment by UnknownShadow200** [comment]
Cw maps saved by client only save lower 8 bits of block ids and data for
first 256 custom blocks.

**Comment by TheRealPear** [comment]
Would it be possible to get it with the right blockdef?

**Comment by TheRealPear** [comment]
This is pretty old and I no longer have the need to import this map anymore. Closing this.

**Comment by UnknownShadow200** [comment]
Still an issue others have raised, and I do intend to eventually fix this at some point.

**Comment by UnknownShadow200** [comment]
Okay took quite a while but implemented as of a999995fd2e9bb026042af16378092999cf7b7d5.
