### ISSUE TITLE
Duplicate "else" in latest commit. 

### ISSUE THREAD

**Issue by eddynetweb** [ClassiCube/MCGalaxy#511]
You got a little `else` there in https://github.com/UnknownShadow200/MCGalaxy/commit/0b07054ceb4c68b5ac2e11c5e466689946e1cd0c that causes `Commands/Maintenance/CmdServer.cs(97,19): error CS1525: Unexpected symbol else`.

https://github.com/UnknownShadow200/MCGalaxy/blob/0b07054ceb4c68b5ac2e11c5e466689946e1cd0c/MCGalaxy/Commands/Maintenance/CmdServer.cs#L97

**Comment by UnknownShadow200** [comment]
Oops. I forgot to save the file before pushing
