### ISSUE TITLE
The server only asks admins to set their password upon reconnect.

### ISSUE THREAD

**Issue by Ankeraout** [ClassiCube/MCGalaxy#520]
Steps to reproduce:

- Create a server
- Join the server (you are guest)
- Set your own rank to SuperOP using console
- (the server does not ask you to set your password)
- Close the game and reconnect
- The server asks you to set your password

This is a potential security threat for servers that have name verification disabled.

Screenshots:
![Capture](https://user-images.githubusercontent.com/15966256/68604522-f59ed500-04aa-11ea-8fa2-5c62ab02b70c.PNG)
![Capture2](https://user-images.githubusercontent.com/15966256/68604524-f7689880-04aa-11ea-888b-d1cf17cf9f50.PNG)

**Comment by UnknownShadow200** [comment]
Hmmm I guess so, although really, there is no good reason for a server to
disable name verification in the first place.
