### ISSUE TITLE
SQL server migration error

### ISSUE THREAD

**Issue by skititlez** [ClassiCube/MCGalaxy#521]
migrated the server to a new system with new SQL instance. Did an export of the MySQL and import
Server now throws error
-------------------------
----11/13/2019 10:45:09 PM----
Type: KeyNotFoundException
Source: mscorlib
Message: The given key was not present in the dictionary.
Target: ThrowKeyNotFoundException
Trace:    at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MySql.Data.MySqlClient.CharSetMap.GetCharacterSet(DBVersion version, String CharSetName)
   at MySql.Data.MySqlClient.CharSetMap.GetEncoding(DBVersion version, String CharSetName)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at MCGalaxy.SQL.SqlQuery.Iterate(String sql, Object[] parameters, Object arg, ReaderCallback callback)
   at MCGalaxy.SQL.Database.Do(String sql, Boolean createDB, Object arg, ReaderCallback callback, Object[] args)

-------------------------

**Comment by UnknownShadow200** [comment]
Hmm this seems more like an issue with your DB setup, since it's
complaining about missing charset in mysql.data. I think you need utf8, but
I will check later today

Also congrats on probably being the only one to use the mysql backend

**Comment by skititlez** [comment]
its been running on the back end for a long long time and that server is shitting the bed so before it failed i figured id bring it over.
The DB is setup for charset/collation of UTF8/UTF8_Bin

**Comment by UnknownShadow200** [comment]
My mistake, it defaults to latin1.

**Comment by skititlez** [comment]
any specific server version?
im using the latest version

**Comment by UnknownShadow200** [comment]
Shouldn't matter.

**Comment by skititlez** [comment]
that still gives the error when a user loads into the server

**Comment by UnknownShadow200** [comment]
If you use mysql workbench, what collation do you see if you right click on the database -> schema inspector? I have latin1_swedish_ci

**Comment by skititlez** [comment]
Well i managed to bypass the issue. Not to sure but the issue is with SQL 8.0
I installed SQL 5.7 the latest update to it and imported the database and it resolved the issue. I would have tried earlier but health issues on my side have been preventing me from troubleshooting and trying this out.

**Comment by UnknownShadow200** [comment]
Ah, that's the cause. Turns out the [default charset](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_character_set_server) got changed to utf8mb4 in 8.0.1, but the version of mysql.data.dll included with MCGalaxy is so old (6.3.0 from 2010!) that it doesn't support it. Oops.

**Comment by skititlez** [comment]
Whoops lol. at least the problem is. imma say this is closed then
