### ISSUE TITLE
Idea for custom block particles via /gb

### ISSUE THREAD

**Issue by MasterlazorX** [ClassiCube/MCGalaxy#525]
Basically the title explains it, the blocks can have a particle emit based on defined pixel coorinates and a custom particle used is based in the particles.png (which could use a .txt to coordinate a specific particle in the same way as animated blocks)

The particle could have some presets where behave like rain or flame and smoke and a lava "pop" (others like a torch or furnace, lava or even fire, for instance) and the user can customize how these behave, even if they want these particles to freeze in place or go nuts.
Clients have an option to turn custom particles off, and an option via /gb to make these particle events random within a defined time or strict interval.

There should be an option lastly, to define the "lifespan" of the particle and leaving this empty would default to what at or near Minecraft value.
This feature should be considered since I think it could bring life to many servers.

**Comment by UnknownShadow200** [comment]
Note: depends on https://github.com/UnknownShadow200/ClassiCube/issues/625

**Comment by UnknownShadow200** [comment]
Implemented in the game thanks to Goodly
