### ISSUE TITLE
Economy Map Bug

### ISSUE THREAD

**Issue by EmpyTM** [ClassiCube/MCGalaxy#531]
If a rank's /gen volume limit were set lower than the limit allotted in an economy map's preset size, and the ranked player attempted to buy that map, the server would notify the player that they cannot create a large enough map, a **System.NullReferenceException** would be thrown, and the map would not be purchased.

**Comment by UnknownShadow200** [comment]
There are servers actually using this feature??

Will fix though.

**Comment by EmpyTM** [comment]
I decided to do what no one else was doing and mess around with economy. Will let you know if I find any more

**Comment by UnknownShadow200** [comment]
Should you be able to buy the map still?

**Comment by EmpyTM** [comment]
I could see both options working honestly. if you wanted a larger map than you could generate yourself you could opt for buying it instead. alternatively, withholding buying the map could allow for rank-specific map presets. what do you think?

**Comment by UnknownShadow200** [comment]
I'm not sure which behaviour is better - since you're the one who will you actually use this feature, I'll go with the choice you pick.

**Comment by EmpyTM** [comment]
Well assuming you can still generate maps with /os, a server expecting you to buy a preset wouldnt want you to just create one without spending on the server, so i would guess the former would be better.

**Comment by UnknownShadow200** [comment]
Fully implemented by 6a03bffebeed4cdfa43004e42a6294a6db0ad624.
