### ISSUE TITLE
Port forward broken

### ISSUE THREAD

**Issue by Rubiktor012** [ClassiCube/MCGalaxy#536]
I've got a ClassiCube server and the forward has been messed up sometimes, but it was fixable by deleting the forward and creating a new one. But now, the forward messed up and when I click the "Forward 25565" to the "Delete forward" buttons, it will just say "Error contacting router." in red text.

Is my server broken? Or is it my router?

**Comment by UnknownShadow200** [comment]
The two main reasons why MCGalaxy would be unable to contact the router
a) uPNP is disabled on the router
b) The router returns an unrecognised response

Given the wide range of routers out there, it's possible I do not handle what the router is returning now. You could try this [debug version](https://github.com/UnknownShadow200/MCGalaxy/files/4716424/MCGalaxy.zip), which will log upnp query/response in the main window's logs

![image](https://user-images.githubusercontent.com/6509348/83508727-b0f18e80-a50d-11ea-859c-5322f3792924.png)

**Comment by Rubiktor012** [comment]
Somehow, the uPNP is not logging into the main window, or anywhere else. I replaced the normal .exe with the debug .exe

**Comment by Rubiktor012** [comment]
It will just say `### Sending UPNP query` and it will give no response. I got it to work with UPNP at first.

**Comment by Rubiktor012** [comment]
Sorry for closing the issue, it was an accident :/

**Comment by UnknownShadow200** [comment]
If your router doesn't reply at UPNP query, there isn't anything I can do.
