### ISSUE TITLE
I can only connect to my server by the web client

### ISSUE THREAD

**Issue by MESYETI** [ClassiCube/MCGalaxy#542]
If I try to connect to my MCGalaxy server from the ClassiCube game launcher, it won't connect, but if I connect from the ClassiCube web client, it connets

**Comment by UnknownShadow200** [comment]
Are you trying to connect to your own server via the server list or via [direct connect](https://github.com/UnknownShadow200/MCGalaxy#joining-from-the-desktop-client)?
