### ISSUE TITLE
It says MCgalaxy_.dll is missing and I clearly have it

### ISSUE THREAD

**Issue by s64502429** [ClassiCube/MCGalaxy#563]
![Capture](https://user-images.githubusercontent.com/69979107/95677002-9650b580-0b90-11eb-9bd6-c891f164c4ba.PNG)

**Comment by UnknownShadow200** [comment]
Can you please screenshot the folder

**Comment by s64502429** [comment]
Never mind, I put the files in a new folder than ran it and it worked.

**Comment by Goodlyay** [comment]
Was it originally in a zip file?

**Comment by ghost** [comment]
You can't have a game extract files in a zip, or, you can't run most of many programs and games properly in a zip.

**Comment by s64502429** [comment]
It was in a .Zip file originally.

**Comment by UnknownShadow200** [comment]
I've changed the error message in 2f07581133e05be03fedd029deca8c323aecbfcb so MCGalaxy will also report which folder it was trying to find MCGalaxy_.dll in.

![image](https://user-images.githubusercontent.com/6509348/95801330-bc6b8680-0d45-11eb-92e5-89c0bc298ce2.png)
