### ISSUE TITLE
Cannot update server because Updater.exe is missing from MCGalaxy Git Source

### ISSUE THREAD

**Issue by NBBStarB** [ClassiCube/MCGalaxy#564]
The file isnt in the Git and will now not allow me to update my server

**Comment by UnknownShadow200** [comment]
Does Updater.exe in the Uploads folder not work?

**Comment by UnknownShadow200** [comment]
Separate Updater.exe is no longer used as of b1d78252379f81362f2a29857936ac1d2b6ac70e
