### ISSUE TITLE
[Suggestion] Running the Server without GUI

### ISSUE THREAD

**Issue by melroy89** [ClassiCube/MCGalaxy#570]
Hi,

As a dedicated server owner, I do **not** want and I don't need a GUI. Just starting the server and put the logging to some file (or ideally to stdout/stderr).

If you need settings, just create a separate configuration file that gets read by the server during startup.

Regards,
Melroy van den Berg

**Comment by andrewphorn** [comment]
Good thing you can launch `MCGalaxyCLI.exe` to run the server without a GUI.

**Comment by melroy89** [comment]
How? It's not explained in the Readme.

**Comment by melroy89** [comment]
@andrewphorn  sorry you are right, there is a separated executable for that. -,- my bad.
