### ISSUE TITLE
Countdown breaks if started by server autostart without any speed defined

### ISSUE THREAD

**Issue by forkiesassds** [ClassiCube/MCGalaxy#578]
If you have countdown start on server startup and not set default speed rounds won't start.

**Comment by alexsssz** [comment]
What server did you try this on and what countdown difficulty? A countdown game has been running on mine for the past couple of days and it seems normal. (difficulty is set to extreme though, so it's fast, but not faster than when it started)

**Comment by forkiesassds** [comment]
> 
> 
> What server did you try this on and what countdown difficulty? A countdown game has been running on mine for the past couple of days and it seems normal. (difficulty is set to extreme though, so it's fast, but not faster than when it started)

I'm running countdown on the default settings /cd start uses.

**Comment by forkiesassds** [comment]
Turns out it wasn't due to the fact it was running for quite some time.
