### ISSUE TITLE
Closing the game while hidden will show an extra disconnection message

### ISSUE THREAD

**Issue by FabTheZen** [ClassiCube/MCGalaxy#58]
When you do /hide, it will send a disconnect message ([Player] has disconnected), when you actually log off, there will be another one sent, and that blows the cover off. It's inconvenient, any chance we can have that fixed? ty

**Comment by Venom983** [comment]
Are you still having this issue? Because when tested it seems to show only the initial /hide logout message and no extra as you have stated. If you use /quit then of course it'll show another message, you're being kicked not disconnecting.

**Comment by FabTheZen** [comment]
Yes I am still having it, just tested it

**Comment by UnknownShadow200** [comment]
Only seems to happen on Fab's server for some reason, doesn't happen when tested on 1.7.3.0 or in the latest builds.

**Comment by FabTheZen** [comment]
Still does it, but I'm closing this since it must be a problem with my stuff

**Comment by Venom983** [comment]
It actually an issue with the ForgeBot itself. Problem being that it doesn't check if a player was hidden prior to disconnecting so it'll always send the disconnection message.

Should be fixed in https://github.com/Hetal728/MCGalaxy/pull/93

**Comment by FabTheZen** [comment]
Ohh sweet! Thank you Ven :D
