### ISSUE TITLE
Spamming /me does not auto-mute you

### ISSUE THREAD

**Issue by forkiesassds** [ClassiCube/MCGalaxy#580]
People can use /me to constantly spam chat and annoy other players due to the fact that using that command won't mute you.

**Comment by UnknownShadow200** [comment]
Are you sure automute is enabled?
![image](https://user-images.githubusercontent.com/6509348/108139700-bda62900-7114-11eb-92bd-e93a0185ba70.png)

**Comment by forkiesassds** [comment]
Oh, I guess I forgot to enable that.
