### ISSUE TITLE
Only SuperOP+ can draw with unknown.

### ISSUE THREAD

**Issue by rdebath** [ClassiCube/MCGalaxy#582]
The user has permission "AdvBuilder", they are also on their own realm.
Commands ...
```
/brush cloudy rose/1 skip/5 s=3004
Set your brush to Cloudy
/cuboid
Only SuperOP+ can draw with unknown.
```

If I replace the "skip" with "stone" it allows the drawop and asks for the two corner blocks. 
It seems very wrong to need SuperOP to have the ability to NOT draw a block.

**Comment by UnknownShadow200** [comment]
Accidentally introduced this bug in ae9a20e2fbf082abb0a595fa679bbe4ccbf4261d when doing minor code tidy up, didn't notice it as I usually test things as superop. Will get this fixed
