### ISSUE TITLE
Disable "Firespike" glitch

### ISSUE THREAD

**Issue by rdebath** [ClassiCube/MCGalaxy#586]
Turn on "physics==1".

If you create a pillar of wood, wool or anything with "LavaKills" set and place a ring of fire around it you get a (more or less) permanent pillar of fire dropping blocks on anything below.

This doesn't work with "physics2" so I suggest the below workaround ... It calls "ExpandAdvanced" at a very low probability (1 in 999) even in "physics1" this means that the "firespike" will start up, but after a couple of minutes it'll go out.

Note1: This deletes a few of the pillar blocks to break it up so each section is no longer tall enough to sustain the reaction. This is something like the effect you get if you have a 2x1 tower except in normal "physics1" the whole 2x1 tower is removed.
Note2: lvl.MakeExplosion may be called, but this will do nothing because physics is level 1.

I do like the effect that it looks like it's working, but the "griefer" then gets disappointed. :smiling_imp: 

``` diff
diff --git a/MCGalaxy/Blocks/Physics/FirePhysics.cs b/MCGalaxy/Blocks/Physics/FirePhysics.cs
index 0035cf5aa..de9cc7d9b 100644
--- a/MCGalaxy/Blocks/Physics/FirePhysics.cs
+++ b/MCGalaxy/Blocks/Physics/FirePhysics.cs
@@ -86,7 +86,9 @@ namespace MCGalaxy.Blocks.Physics {
                     C.Data.Data++;
                     return;
                 }
+            }

+            if (lvl.physics >= 2 || rand.Next(1, 999) == 1) {
                 ExpandAvanced(lvl, x - 1, y, z);
                 ExpandAvanced(lvl, x + 1, y, z);
                 ExpandAvanced(lvl, x, y - 1, z);
```

**Comment by UnknownShadow200** [comment]
ExpandAdvanced cannot be used here because it destroys existing blocks, which is not supposed to occur at physics level 1. (the fact it does destroy blocks in ExpandDiagonal at physics level 1 is a bug)

**Comment by rdebath** [comment]
Um, isn't the only purpose of the "Fire physics" to destroy blocks? (And maybe later players)

If you don't want that, it seems the only thing left at physics1 would be for fire to go out after a short time. I suppose you could make it like Leaves, so it has to be sitting on top of a "lavakills" block or magmablock/magma/lava to hang around. Otherwise it seems a bit pointless to even enable it (at level 1) without destruction as having the fire spread would be a bad idea, it would be just another pointless flood fill.

**Comment by UnknownShadow200** [comment]
Which happens at physics level 2. It isn't supposed to destroy blocks at level 1 because lava/water do not burn/flood blocks at physics level 1

**Comment by rdebath** [comment]
Actually, to be pedantic, water destroys lava blocks. This means `/unflood` leaves some debris behind if they interact.

Anyway, it looks like the fix you want is to stop calling `ExpandDiagonal` at physics1. That's fine by me it'll cure this too, though I suspect I'll just set the OPBlock bit for the fire block.

Should I close this issue?

**Comment by UnknownShadow200** [comment]
b26e4f98c47ab54f0304028494c58ec93b588129 should address this

**Comment by rdebath** [comment]
Checked. Fire goes away, can't get anything to burn. Physics updates clear.
Looking good. 

Physics-2 still works as before.
