### ISSUE TITLE
/Ascend gives error "No free spaces found above you"

### ISSUE THREAD

**Issue by rdebath** [ClassiCube/MCGalaxy#589]
Um ... What!?

You can always `/tp` above the highest buildable block.

**Comment by Goodlyay** [comment]
Please provide more context? Ideally a world file along with coordinates where the command isn't working properly.

**Comment by rdebath** [comment]
On a small "Empty" map (128 64 128 IIRC) I did this:
```
/z 1
/m 0 3 0
/m 999 999 999
/ascend
```
All blocks up to the upper limit of where you can place a block were filled, but obviously there's still space you can `/tp` to above that point. The `/ascend` command did not port me up but `/tp ~0 999 ~0` did (though obviously a bit high).

**Comment by Goodlyay** [comment]
Thanks, 118439a8489365a87b52b2fbd8abf6a7b893a0fc
