### ISSUE TITLE
/clear doesnt clear full 30 lines of chat

### ISSUE THREAD

**Issue by ProgramPL** [ClassiCube/MCGalaxy#601]
![image](https://user-images.githubusercontent.com/72346428/116704634-a21f9000-a999-11eb-8a20-9de70f1a508d.png)

in the top left corner chat can still be seen after using /clear

**Comment by UnknownShadow200** [comment]
Should have been fixed by 898b4c75ee024c92de91ada4bf79ab63e2769973 already, server may be outdated

**Comment by ProgramPL** [comment]
Is NA2 outdated on 1.9.2.9 then?

**Comment by UnknownShadow200** [comment]
yes
