### ISSUE TITLE
Expose CmdResizeLvl.ResizeLevel 

### ISSUE THREAD

**Issue by rdebath** [ClassiCube/MCGalaxy#603]
Please make `MCGalaxy.Commands.World.CmdResizeLvl.ResizeLevel` available to a plugin/loadable command.

eg:...

``` diff
diff --git a/MCGalaxy/Commands/World/CmdResizeLvl.cs b/MCGalaxy/Commands/World/CmdResizeLvl.cs
index 0895b1887..8e02d23e6 100644
--- a/MCGalaxy/Commands/World/CmdResizeLvl.cs
+++ b/MCGalaxy/Commands/World/CmdResizeLvl.cs
@@ -67,7 +67,7 @@ namespace MCGalaxy.Commands.World {
             return true;
         }

-        static Level ResizeLevel(Level lvl, int width, int height, int length) {
+        public static Level ResizeLevel(Level lvl, int width, int height, int length) {
             Level res = new Level(lvl.name, (ushort)width, (ushort)height, (ushort)length);
             res.hasPortals       = lvl.hasPortals;
             res.hasMessageBlocks = lvl.hasMessageBlocks;
```

**Comment by UnknownShadow200** [comment]
Two issues here:

1. As a general rule built-in commands should not be exposing parts of their code to custom plugins
2. ResizeLevel is not a safe operation to expose to plugins, as it does things such as hijacking original level's zones list and disables saving changes to the original level anymore. The only thing that can really be done with the returned level instance is just `LevelActions.Replace` anyways

**Comment by rdebath** [comment]
1. This is a complete process. It does all the steps to create a resized level.
2. The only reason it is "unsafe" is because includes a second incomplete function. You say it yourself, it does the first part of the `LevelActions.Replace` so the caller must complete that second step (which I'm actually doing).

We can of course fix that...

``` C#
        public static Level ResizeAndReplaceLevel(Level lvl, int width, int height, int length) {
            Level resized = CmdResizeLvl.ResizeLevel(lvl, width, height, length);
            LevelActions.Replace(lvl, resized);
            return resized;
        }
```

BTW: `DoResize` is not appropriate. It does parsing, it has fuzzy matching on the level name, it breaks the ref you have to the level and it depends on the Player object.

**Comment by UnknownShadow200** [comment]
1. What I mean is that `Command` classes should not be exposing general public functions - belongs in dedicated classes like LevelActions etc
2. `DoResize` was made public on accident, fixed in bb3ad2c2099e85b4658b02441514e3c437091b47
3. such a function should return `void` to make it clear that the original level is being overwritten, not returning a resized copy of it

**Comment by rdebath** [comment]
1. In that case please move the `ResizeAndReplaceLevel` function (or maybe just `ResizeLevel`) into `LevelActions` where it belongs.
2. Okay I guess.
3. NO. Returning void would mean that it'll do it's job to the object you gave. It most definitely does not mean that you have to discard the object you gave it. The `Replace` function name is a bit better, because it's requesting that the level be replaced in all the normal global references. But there's no reason to expect an action that's applied to an object (like resize) to invalidate all references to that object so something like "returning void" is just going to say it has no normal failure modes. BUT, returning a new Level object begs the question as to why that's being done, with the obvious answer (after scanning the code) being that it's working like the String class and creating a new copy of the object rather than doing the resize to the existing object.

**Comment by UnknownShadow200** [comment]
Except that the methods in the String class return a new string while leaving the input string untouched - this definitely modifies the input level (and also renders the input level essentially useless when combined with `LevelActions.Replace` as that unloads it)

----

Could consider doing `void Resize(ref Level lvl)` and set `lvl = resized;` at the end instead, similar to what .NET's Array.Resize does

**Comment by rdebath** [comment]
That makes sense, I'd forgotten that you have to decorate `ref` and `out` parameters on the call. (Seems like my plan to learn C# is starting to work)

**Comment by UnknownShadow200** [comment]
Does 1a998d6bf770f8242f76d55b7c612587ff10c58a address this?

**Comment by rdebath** [comment]
Basic testing is working fine. I can call it successfully and populate the returned level with new contents. Including blocks, block definitions and block properties.

Yes. Thankyou.
