### ISSUE TITLE
Messageblock continues to run after Logoff/Kick.

### ISSUE THREAD

**Issue by rdebath** [ClassiCube/MCGalaxy#604]
Seems like a bad idea to let players run commands after they're logged off. This'd stop it.

``` diff
diff --git a/MCGalaxy/Player/Player.Handlers.cs b/MCGalaxy/Player/Player.Handlers.cs
index 32b8275d9..99bafe05f 100644
--- a/MCGalaxy/Player/Player.Handlers.cs
+++ b/MCGalaxy/Player/Player.Handlers.cs
@@ -698,6 +698,7 @@ namespace MCGalaxy {
         bool UseCommands(List<Command> commands, List<string> messages, CommandData data) {
             for (int i = 0; i < messages.Count; i++) {
                 if (!UseCommand(commands[i], messages[i], data)) return false;
+                if (leftServer) return false;
             }
             return true;
         }
```

**Comment by UnknownShadow200** [comment]
Is this a change you would particularly take advantage of? 

(Note: general indication after asking around is that this change would not cause any problems)

**Comment by rdebath** [comment]
It's not essential, in the event that my "zombie bob" getting out of control I can bounce the service.
It's not as if there are a dozen users I'll impact. (Though I'll probably leave it in as a local patch)

The main problem I see with running user code when they're logged off is if they were kicked/banned. But checking that would probably be expensive whereas this is a, cheap, trivial check.

**Comment by UnknownShadow200** [comment]
Makes sense why you'd want it then - does b28c1ab70cd2ded56bb3721718c657551b4a3fba address this?

**Comment by rdebath** [comment]
Exactly as requested, thanks.
