### ISSUE TITLE
Misleading log message in Server Init, should be placed in ClassiCube Heartbeat implementation

### ISSUE THREAD

**Issue by johannespartin** [ClassiCube/MCGalaxy#626]
In the Server Init method `static void InitRest(Scheduler Task)` the following message is logged: "Finished setting up server, finding classicube.net url.."

This should be implemented once the uuid is requested within the heartbeat implementation.

https://github.com/UnknownShadow200/MCGalaxy/blob/16cc7085013bc7f5ad38ea9871293b7c4b98c348/MCGalaxy/Server/Server.Init.cs#L137

**Comment by UnknownShadow200** [comment]
Does 2e1c4e9b61a06716060a7af8fa3de4ed1a68015f resolve this?

**Comment by johannespartin** [comment]
Looks good to me. Thank you!
