### ISSUE TITLE
/os blockprops [id] odoor [block] can be used to bypass block permissions

### ISSUE THREAD

**Issue by xnotx123** [ClassiCube/MCGalaxy#631]
For example, if the block FlagBase is only allowed for moderator+, someone of a lower rank could use the command /os blockprops [id] odoor FlagBase to circumvent the permissions. Note that this user would have no way of destroying the block after placing it.

**Comment by UnknownShadow200** [comment]
It would be very simple to change `/blockprops` to not allow assigning oDoors to block IDs that you are not allowed to modify

Actually preventing oDoors themselves from placing blocks the triggering player is not allowed to would be very difficult

**Comment by xnotx123** [comment]
I think your former suggestion would be perfect.
