### ISSUE TITLE
Multiple user defineable heartbeat adresses.

### ISSUE THREAD

**Issue by forkiesassds** [ClassiCube/MCGalaxy#636]
Might also include prefix or suffix support to allow separation from which server list players joined.

**Comment by MisterSheeple** [comment]
I support this.

**Comment by UnknownShadow200** [comment]
Depends how different the heartbeats need to be: Just sending the same heartbeat (with differing salt) to multiple providers isn't too tricky. But if a heartbeat provider requires different fields to be sent, that's much more difficult

**Comment by MisterSheeple** [comment]
> Depends how different the heartbeats need to be: Just sending the same heartbeat (with differing salt) to multiple providers isn't too tricky. But if a heartbeat provider requires different fields to be sent, that's much more difficult

If I'm not mistaken, Betacraft's heartbeat is more or less similar to ClassiCube's, so if adding support for more heartbeats needs to be done on a per-provider basis, I don't think adapting Betacraft would be that difficult of a thing to do.

**Comment by forkiesassds** [comment]
Possibly allow users to like arrange the heartbeat URL as a string or something like that.

**Comment by MisterSheeple** [comment]
actually hold on, I know for fact this should be an easy job and here's why:

I've outright replaced the classicube heartbeat with betacraft in the past and everything worked fine. i doubt many (if any) changes would have to be made. Please consider adding support for this.

**Comment by craftycodie** [comment]
Picking up this task.

**Comment by UnknownShadow200** [comment]
fyi I am currently working on this

**Comment by craftycodie** [comment]
> 
> 
> fyi I am currently working on this

Spotted that a little too late lol.
PR'd anyway, curious to see how our implementations differ.

**Comment by forkiesassds** [comment]
The reason why I suggested an option to include a prefix or suffix for players that join from certain server lists is so if a server list uses a different auth system from other server lists it would help preventing impersonation of players that come from server list x by registering someone's username on server list y and joining the server they want to impersonate on.
