### ISSUE TITLE
Searching players in PlayerDB should preffer case-sensitive search first instead of case-insensitive

### ISSUE THREAD

**Issue by forkiesassds** [ClassiCube/MCGalaxy#637]
This avoids cases when someone is looking up for PlayerAmazing, but the player database has both playeramazing and PlayerAmazing, and in some cases it might prefer the name with the wrong cases instead of the one the user might be looking for.

**Comment by UnknownShadow200** [comment]
Having multiple of same username but with different case is unsupported
