### ISSUE TITLE
Allow disabling of certain CPE features.

### ISSUE THREAD

**Issue by forkiesassds** [ClassiCube/MCGalaxy#639]
For instance some people might want the CustomBlocks extension to be disabled, but keep most of the other CPE features enabled like the env features.

**Comment by rdebath** [comment]
I would suggest this is supported by an event in `MCGalaxy/Player/Player.CPE.cs`, at the start of either `FindExtension` or `AddExtension`. This event may also be useful to *add* support for a simple extension.
