### ISSUE TITLE
Add a config option to allow/disallow the joining of certain Classic versions

### ISSUE THREAD

**Issue by MisterSheeple** [ClassiCube/MCGalaxy#641]

**Comment by UnknownShadow200** [comment]
What's the use of intentionally preventing some versions from joining?

**Comment by MisterSheeple** [comment]
> What's the use of intentionally preventing some versions from joining?

Some people like hosting servers specifically for one version of the game so they can have an experience strictly reminiscent of that particular version.

**Comment by UnknownShadow200** [comment]
I don't think it should be MCGalaxy's job to restrict players based on their client - best done with a plugin (e.g. see [this example](https://github.com/ClassiCube/MCGalaxy-Plugins/blob/master/KickNoCC.cs) for reference)

I made the `ProtocolVersion` field public, so you can use `p.ProtocolVersion` to determine the appropriate action to perform based on the client's version

**Comment by MisterSheeple** [comment]
> I don't think it should be MCGalaxy's job to restrict players based on their client - best done with a plugin (e.g. see [this example](https://github.com/ClassiCube/MCGalaxy-Plugins/blob/master/KickNoCC.cs) for reference)
> 
> I made the `ProtocolVersion` field public, so you can use `p.ProtocolVersion` to determine the appropriate action to perform based on the client's version

Ah alright then, thanks.
