### ISSUE TITLE
Auth fails on protocol 3 clients.

### ISSUE THREAD

**Issue by forkiesassds** [ClassiCube/MCGalaxy#642]
If auth is enabled, and you if you try connecting to the server using a protocol 3 client it will disconnect you for invalid mpass.
![image](https://user-images.githubusercontent.com/54495659/135749109-58dadc38-ab27-4f99-acbf-1f2c54a933b6.png)

**Comment by UnknownShadow200** [comment]
Problem is with the client not sending a valid mppass
![image](https://user-images.githubusercontent.com/6509348/135749921-d4dc1ba4-8aca-47a5-92a0-d91999260b66.png)

**Comment by MisterSheeple** [comment]
Verify-names is not present in protocol 3 versions, therefore the client doesn't send an mppass at all, so this isn't a bug. Auth was not added until protocol 4 (0.0.17a). This issue should probably be closed.
