### ISSUE TITLE
Remove devs.txt

### ISSUE THREAD

**Issue by forkiesassds** [ClassiCube/MCGalaxy#645]
devs.txt hasn't been updated for quite a while, and it contains developers that are no longer active contributors to MCGalaxy.

**Comment by UnknownShadow200** [comment]
Is there a reason for wanting it to be removed? 
Although the file is no longer used, I left it there so /devs would still work properly  (and to avoid 'error updating staff list' error message) on much older versions of MCGalaxy running on mono

**Comment by forkiesassds** [comment]
I was talking about like stuff that still uses devs.txt to this day, including /whois mentioning if they are a developer.

**Comment by UnknownShadow200** [comment]
devs.txt isn't used anymore, that command uses `Devs` field from Server.Fields.cs
