### ISSUE TITLE
Across the internet.

### ISSUE THREAD

**Issue by xzzjs** [ClassiCube/MCGalaxy#654]
Hello, When I click the url it give me an error and says "Sorry, No server has that hash"

**Comment by UnknownShadow200** [comment]
Are you clicking the URL in the URL textbox, or the URL in the main logs textbox?
![image](https://user-images.githubusercontent.com/6509348/140443586-8c7312a9-18b5-4d91-8b03-64f5cf407260.png)

Do you consistently have this issue?

**Comment by UnknownShadow200** [comment]
@MEEBLOXAlt ?

**Comment by UnknownShadow200** [comment]
No response received. If you're still having issues, feel free to reopen

**Comment by xzzjs** [comment]
I thought I could make the server online but I've figured it out.
