### ISSUE TITLE
Allow changing protocol version to send to heartbeat.

### ISSUE THREAD

**Issue by forkiesassds** [ClassiCube/MCGalaxy#667]
This is helpful on certain server lists like Betacraft, to tell which version to connect with.

**Comment by UnknownShadow200** [comment]
All classic protocol versions are supported, so what advantage is there to specifying a lower version in the heartbeat?

**Comment by forkiesassds** [comment]
It's to set the default version.

**Comment by UnknownShadow200** [comment]
Was there a reason of closing? 
I'm not opposed to the idea altogether, just been a bit busy and haven't been able to allocate much time for MCGalaxy at the moment
