### ISSUE TITLE
Trying to /fill with still water fills the entire world

### ISSUE THREAD

**Issue by popdynamite5511** [ClassiCube/MCGalaxy#727]
When selecting an area to fill with still water, it fills the entire world instead of the selected area I want it to fill.

**Comment by UnknownShadow200** [comment]
Do you have block physics on or off?

**Comment by popdynamite5511** [comment]
Physics are on, however the block is still water so it probably shouldn't be spreading.
Since the server this was happening on wasn't my server, I just tried opening a test server, turned the physics off and tried to /fill using still water, it also filled the entire world with it, so this seems to happen with all physics modes.

**Comment by popdynamite5511** [comment]
Oh wait I'm stupid lol, this is working as intended I believe. The cuboid command is the one I want
