### ISSUE TITLE
Not opening on Windows XP VM 

### ISSUE THREAD

**Issue by popdynamite5511** [ClassiCube/MCGalaxy#729]
![Screen Shot 2022-11-16 at 11 55 17 AM](https://user-images.githubusercontent.com/96096000/202281471-16656377-005c-427f-8197-7118e3f15746.png)
Gives this error code upon startup
I am using VirtualBox, not sure if this is really a fixable bug since some issues with programs in VirtualBox aren't fixable but I am reporting this just in case

**Comment by UnknownShadow200** [comment]
Do you have .NET 4.0 installed?

**Comment by popdynamite5511** [comment]
As far as I know, I don't - I'll try installing it

**Comment by popdynamite5511** [comment]
It seems to work now

**Comment by popdynamite5511** [comment]
l
