### ISSUE TITLE
Make it so it bypasses /pass verification if player's rank is too low to use /pass

### ISSUE THREAD

**Issue by forkiesassds** [ClassiCube/MCGalaxy#734]
This leaves a security vulnerability but fixes an issue with improperly configured servers.

**Comment by UnknownShadow200** [comment]
`/pass` already gets special treatment, so shouldn't be too much effort to also allow the command to execute without the usual command permission checking

**Comment by forkiesassds** [comment]
8c9f0e60ea6488806ad625755c7182d0ec6c7578 has solved the issue, although in a different way.
