### ISSUE TITLE
/deletelvl final backup is broken

### ISSUE THREAD

**Issue by rdebath** [ClassiCube/MCGalaxy#736]
Seems this isn't logged...

If you do a `/deletelvl levelname` the current level file is moved to the `levels/deleted` directory.
BUT the other normal backup files (`blockdefs.json`, `blockprops.txt` and `map.properties`) are lost.
I'd suggest the final backup should be stored under `levels/backups` the same way all the others are.

**Comment by UnknownShadow200** [comment]
Same issue as #650 ?

**Comment by rdebath** [comment]
Yup, added the search term.
