### ISSUE TITLE
Undo/BlockDB format needs a major overhaul.

### ISSUE THREAD

**Issue by UnknownShadow200** [ClassiCube/MCGalaxy#74]
Let's look at a few typical lines:
main 0 200 0 10/31/2015&18:42:16 141 0 
main 10 0 1 10/31/2015&18:42:16 203 0 
- Position could be stored as 3 ushorts.
- Date could be stored as a unix timestamp
- New block and old block could be stored as two bytes.

About map name, might be difficult now, but perhaps a 'chunking' mechanism could be implemented so that the format is instead:
main 400
0 200 0 10/31/2015&18:42:16 141 0 
...
etc up to 400 entries.

Edit: Why are you using foreach ( UndoPos uP in p.UndoBuffer.ToList() )?

Edit: Could also consider using relative UInt16 timestamps.

**Comment by Venom983** [comment]
But new block and old block go back farther than just two block changes.

**Comment by UnknownShadow200** [comment]
Yes, but each undopos entry only has old block and new block.

**Comment by UnknownShadow200** [comment]
Done in 07d5c08df6f6699bcf04ea71c21436da948c6a10.
