### ISSUE TITLE
R.I.P Website

### ISSUE THREAD

**Issue by Dinosaurismus** [ClassiCube/MCGalaxy#77]
R.I.P mcgalaxy.ml

**Comment by ghost** [comment]
RIP

**Comment by Dinosaurismus** [comment]
PLEASE REVIVE IT DR HETAL!

**Comment by ghost** [comment]
The patient died of cardiac arrest.

**Comment by UclCommander** [comment]
Confirmed death - 2k15

May classic rip in hell
