### ISSUE TITLE
Issue with texture packs

### ISSUE THREAD

**Issue by RandomStrangers** [ClassiCube/MCGalaxy#773]
Due to Dropbox updating its share URL for texture packs, MCGalaxy will not allow you to use any newer links, it requires the key at the end, but MCGalaxy requires it to end in a file extension.
![Screenshot (54)](https://github.com/UnknownShadow200/MCGalaxy/assets/110739593/63cbc292-468d-44bd-8d79-9b2121c7bf1c)
And removing the key at the end results in a 403 error.
![Screenshot (55)](https://github.com/UnknownShadow200/MCGalaxy/assets/110739593/84b30690-783b-4c2c-b93a-e2ca48bd284d)

You can bypass this with a URL shortener, though, but some URL shorteners will not keep the file extension at the end of the URL.

**Comment by UnknownShadow200** [comment]
Should be addressed with latest ClassiCube and MCGalaxy commit
