### ISSUE TITLE
Android version?

### ISSUE THREAD

**Issue by ErickN13** [ClassiCube/MCGalaxy#780]
It would be cool if this version of ClassiCube had an Android version, as not everyone in the world has a PC

**Comment by Goodlyay** [comment]
There are plenty of options for those who want to host a server but do not have a PC. For instance, https://eddyn.net/projects/games/ provides free hosting service for ClassiCube.

Also, just to be clear, MCGalaxy is not a "version" of ClassiCube, it is a multiplayer server software for ClassiCube. You can already play ClassiCube on android. https://www.classicube.net/download/#dl-android

**Comment by ErickN13** [comment]
> There are plenty of options for those who want to host a server but do not have a PC. For instance, https://eddyn.net/projects/games/ provides free hosting service for ClassiCube.
> 
> Also, just to be clear, MCGalaxy is not a "version" of classicube, it is a multiplayer server software for ClassiCube. You can already play ClassiCube on android. https://www.classicube.net/download/#dl-android

Got it bro, Thanks for the information
