### ISSUE TITLE
Un`/follow`ed players remains invisible

### ISSUE THREAD

**Issue by dflat2** [ClassiCube/MCGalaxy#793]
There seem to be a bug in the `Unfollow` method, causing unfollowed players to remain invisible from the operator who followed them.

https://github.com/ClassiCube/MCGalaxy/blob/c860f64c0e22d86f1716c57bfd76e91d1617dd68/MCGalaxy/Commands/Moderation/CmdFollow.cs#L51

```
p.following = "";

Player target = PlayerInfo.FindExact(p.following);
```

The `target` player is always `null`.

**Comment by 123DMWM** [comment]
Thanks. Fixed in b23decdcacdc1aa6e1c1de35336112c753491be0
