### ISSUE TITLE
/search players always showing 100 players on single letter searches (found on NA2)

### ISSUE THREAD

**Issue by kilgorezer** [ClassiCube/MCGalaxy#812]

**Comment by kilgorezer** [comment]
![image](https://github.com/user-attachments/assets/fe3509ed-1a55-4552-bef8-808a38c19a84)

**Comment by Goodlyay** [comment]
This isn't a bug. It intentionally stops at 100 results in order to prevent abuse where querying large databases takes up a bunch of processing power.
