### ISSUE TITLE
Overseer additions: /os save - /os restore

### ISSUE THREAD

**Issue by FabTheZen** [ClassiCube/MCGalaxy#91]
As per title, I've been requested by multiple players such command, that would allow you to save and restore map backups for players in their own overseer maps
Side note: an "/os move" feature would also be nice - mimicking /move but for overseer maps

**Comment by FabTheZen** [comment]
Idk how to modify the thread, anyway please don't mind /os move, we don't need that. On the other hand, a /tppos could somewhat be useful - if I get anyone to be interested in this feature I'll report here (so for now just ignore the side note, thanks)

**Comment by Venom983** [comment]
Move (otherwise kick) already exists as does saving. Refer to line 216 of CmdOverseer.cs.

Use '/os map save' while in-game.

**Comment by FabTheZen** [comment]
Thank you, I wasn't aware of /os map save, anyway there's no /os map restore (but it matters less), and /move moves a player in a different xyz place, that's the behavior i meant for /os move, but it's irrelevant
