### ISSUE TITLE
Allow disabling of default dollarsign variables

### ISSUE THREAD

**Issue by FabTheZen** [ClassiCube/MCGalaxy#92]
An issue I found across all times, is been people using $Nick or $IP to scare/threat people, and I have never found a homemade fix for that.
I would love to see them toggle-able from, say, server.properties (possibly individually, but a global toggle would be okay anyway)

**Comment by UnknownShadow200** [comment]
Player/Chat.cs

At the bottom will be the 'ApplyDollarTokens' method, you can remove them from there.

**Comment by FabTheZen** [comment]
Thank you, that's a very useful info, will disable them from there :D
