### ISSUE TITLE
[CPE Addition] Serverside level texturepack (.zip) support

### ISSUE THREAD

**Issue by FabTheZen** [ClassiCube/MCGalaxy#95]
Since latest clients support full per-level texturepack loading, which enables custom GUI, animations (important for fire, lava etc), fonts and more, it would be great to have a command that enables players to set a custom texturepack. 

Since older clients won't support this, MCGalaxy should be able (and technically can) recognize those clients and provide them with the .png texture instead.

**Comment by UnknownShadow200** [comment]
Done in eb8b8a37ccd46e89cd3c9263c35363d4778ce38d, use /texture levelzip and /texture globalzip.

**Comment by FabTheZen** [comment]
yass :D
