### ISSUE TITLE
"/texture level" won't work as fallback option for classicube - "default" texture/texturepack argument

### ISSUE THREAD

**Issue by FabTheZen** [ClassiCube/MCGalaxy#97]
Also, since there's no way of actually removing a custom texture/texturepack, once you set a "levelzip", the .png texture won't ever be shown.

So i also suggest a command like "/texture level default" to reinitialize a level texturepack to the global one

**Comment by UnknownShadow200** [comment]
Confused. /texture levelzip reset works fine?

**Comment by FabTheZen** [comment]
whoops, never knew about "reset". but still ClassiCube clients won't see the png texture in a level if there's a texturepack zip already applied to it

**Comment by UnknownShadow200** [comment]
![client_terrains](https://cloud.githubusercontent.com/assets/6509348/12375352/75671598-bd12-11e5-8bfd-bc5c374aecd3.png)
Png textures seem to work fine there.

**Comment by FabTheZen** [comment]
Apparently it's something related to how webpages respond to requests, using imgur works (as you found out), so this is most likely a ClassiCube problem. Case closed
