### ISSUE TITLE
Enable per-rank configurable "/overseer" map limit

### ISSUE THREAD

**Issue by FabTheZen** [ClassiCube/MCGalaxy#98]
This feature is in the code, but it's not working for some way, so the map limit is only changeable at the source code, for every player globally, by editing OverseerMaps in Player/Group.cs

It would be useful to have such option to work in ranks.properties.

**Comment by UnknownShadow200** [comment]
Fixed in 36f65b0ef09fbbb9e8c45223521e8a63b707fe66.
